<table>
    <tr>
        <th>Username</th>
        <th>User Type</th>
        <th>Member Since</th>
    </tr>
    <?php foreach ($this->users as $user): ?>
    <tr>
        <td><a href="<?php echo $this->baseUrl() . '/user/' . $this->escape($user->getId()); ?>"><?php echo $this->escape($user->getUsername()); ?></a></td>
        <td><?php echo $this->escape($user->getRole()); ?></td>
        <td><?php echo $this->escape($user->getCreatedDate()); ?></td>
    </tr>
    <?php endforeach; ?>

</table>